pipeline {
    agent any
    tools {
        "org.jenkinsci.plugins.terraform.TerraformInstallation" "Terraform"
    }
    parameters {
        string(name: 'WORKSPACE', defaultValue: 'development', description:'setting up workspace for terraform')
    }
    environment {
        TF_HOME = tool('Terraform')
        TP_LOG = "WARN"
        PATH = "$TF_HOME:$PATH"
        ACCESS_KEY = credentials('AWS_ACCESS_KEY_ID')
        SECRET_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    stages {
            stage('TerraformInit'){
            steps {
                dir('jenkins/'){
                    bat "terraform init -input=false"
                    bat "echo \$PWD"
                    bat "whoami"
            }
        }
}
            stage('TerraformFormat'){
            steps {
                dir('jenkins/'){
                    bat "terraform fmt -list=true -write=false -diff=true -check=true"
                }
            }
        }

            stage('TerraformValidate'){
            steps {
                dir('jenkins/'){
                    bat "terraform validate"
                }
            }
        }
            stage('TerraformPlan'){
            steps {
                dir('jenkins/'){
                    script {
                        try {
                            bat "terraform workspace new ${params.WORKSPACE}"
                        } catch (err) {
                            bat "terraform workspace select ${params.WORKSPACE}"
                        }
                        bat "terraform plan -var 'access_key=$ACCESS_KEY' -var 'secret_key=$SECRET_KEY' -out tfplan"
                    }
                }
            }
        }
    }
}