pipeline {
    agent any
    options {
        ansiColor('xterm')
    }
    tools {
        terraform 'Terraform'
    }
    environment {
        ACCESS_KEY = credentials('AWS_ACCESS_KEY_ID')
        SECRET_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    stages {
            stage('TerraformInit'){
            steps {
                dir('jenkins/'){
                    bat "terraform init -input=false"
                    bat "echo \$PWD"
                    bat "whoami"
            }
        }
}
            stage('TerraformFormat'){
            steps {
                dir('jenkins/'){
                    bat "terraform fmt -list=true -write=false -diff=true -check=true"
                }
            }
        }

            stage('TerraformValidate'){
            steps {
                dir('jenkins/'){
                    bat "terraform validate"
                    bat "echo $ACCESS_KEY"
                }
            }
        }
    }
}